language: python
sudo: false
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
install:
    - travis_retry pip install ipython nose requests
    - python setup.py develop
script:
    - python runtests.py
